version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M